### ISSUE TITLE
query format fail

### ISSUE THREAD

**Issue by cchevall** [meteor/docs#124]
Hi,
I'm having an issue with the query format:
the call:
var response = HTTP.call( "GET", route, { params: { fields: [ "type", "message", "story" ] } } );
the actual query done:
http://myroute?fields[]=type&fields[]=message&fields[]=story

**Comment by abernix** [comment]
Did you get this resolved?  Was this something which was happening in your own code?  Was it not your expectation?

You might be interested in: https://github.com/meteor/meteor/pull/8261 and https://github.com/meteor/meteor/pull/8346

While this is a recent change to Meteor (and a change in a positive direction as far as I'm concerned), I'm asking in order to evaluate how this might be affecting others. 🙂

**Comment by cchevall** [comment]
Hi I just rolledback to previous version.

The issue I have is that Facebook graph API in its 2.8 version (wich I use)
is not complient with this serialization format.
But anyway.

Thanks, keep up the good work.

2017-02-13 15:52 GMT+01:00 Jesse Rosenberger <notifications@github.com>:

**Comment by abernix** [comment]
@cchevall That serialization format is not compatible with any version of the Facebook API.  If you'd like to use it, you can do the following:

```js
var fields = [ "type", "message", "story" ].join(',');
var response = HTTP.call( "GET", route, { params: { fields: fields } } );
```

(Basically, you'll want to join the array into a comma-delimited string, which is what their documentation asks for).

**Comment by cchevall** [comment]
Yep. Thank you.
