### ISSUE TITLE
What's up with version-NEXT branch

### ISSUE THREAD

**Issue by RickvdP** [meteor/docs#143]
Hi,

Didn't find a way to get in touch so just raising it as an issue here. I'm in the middle of updating a bunch of references from the meteor core to the old github wiki, but I'm finding a lot of pages of the old wiki not forwarding to the guide or api docs, but to docs in the version-NEXT branch (whilst already existing in master as well actually)

E.g.
https://github.com/meteor/meteor/wiki/AppCache -> https://github.com/meteor/docs/blob/version-NEXT/long-form/appcache.md
https://github.com/meteor/meteor/wiki/Build-Machines -> https://github.com/meteor/docs/blob/version-NEXT/long-form/build-machines.md
and many more

Do these long form docs still need to be migrated to the guide? Are they there to stay? Is there a plan here? Any way I can help?

Thanks

**Comment by abernix** [comment]
First of all, thank you very much for taking the time to into this.

The `version-NEXT` branch is used when a new feature for an upcoming Meteor release has been documented for the beta, but the official version hasn't been released yet.  Generally speaking though, and I'm not saying this is ideal in any way, Meteor features get documented just after their official release so the use of this `version-NEXT` branch is relatively infrequent.

Basically, that branch is very out of date, though as you can see those docs are also in the `master` branch.  Furthermore, both of those documents you linked are relatively unnecessary at this stage since build machines are not necessary as of Meteor 1.4 and AppCache has been deprecated (prematurely, but that's [another discussion](https://github.com/meteor/meteor/issues/5982#issuecomment-303885690)) by major browsers and its future was uncertain and not recommendable.

I just updated the `version-NEXT` branch so it's no longer out of date and in-sync with `master`.  I'll close this as I think it's "resolved", but please do feel free to ask additional questions or open more issues (or PRs!) if you find other problems with the docs. :smile:
