### ISSUE TITLE
The use of hashes (#) in titles may be confusing

### ISSUE THREAD

**Issue by teamsteamdev** [meteor/docs#150]
Taking a course on Meteor and loving it, just wanted to offer the perspective of a new developer. :)

I found the use of hashes in the docs titles confusing at first glance. While it may be apparent to a more experienced developer, the way to actually use these methods may be confusing to a newbie.

Here's an example:
### [Mongo.Collection#find([selector], [options])](https://docs.meteor.com/api/collections.html#Mongo-Collection-find)
![meteor-docs](https://user-images.githubusercontent.com/23390212/28379413-2bfd4fae-6c79-11e7-934f-410867787c50.png)

This might be easier for some to understand:
### Mongo.Collection.find([selector], [options])

Lots for respect for the way Meteor takes a potentially complicated ecosystem and provides a much simpler wrapper.

**Comment by abernix** [comment]
The hashes actually have a very specific meaning.  The `#` symbol is meant as a shorthand for `.prototype.` and separates the class from its member; `find` is an instance method of the `Mongo.Collection` class.  I'm not sure where this syntax began (or even what to call it), though I know it exists in Ruby and PrototypeJS docs.

The non-shorthand way to show it would be `Mongo.Collection.prototype.find`. Unfortunately, I'm not sure if this would have made it any more clear to you what this meant as your suggestion to use `Mongo.Collection.find` (a notation which suggests `find` is a static method of `Mongo.Collection`) indicates that you didn't understand that `find` was an instance method of `Mongo.Collection` – this is what the `#` is meant to indicate: `find` is an instance method because it's a method available on an instantiated class of `Mongo.Collection`.  This means the correct way to use it would be along the lines of:

```javascript
const Animals = new Mongo.Collection('animals');
const results = Animals.find({ name: 'Coco' }, { limit: 10 });
```

I'd certainly like to improve this and make it more clear for you if we can, possibly by linking to relevant material about it.  Generally speaking, how could we have made this more clear to you without having to clarify on each section (from a higher level)? Would `Mongo.Collection.prototype.find` have made sense to you?

**Comment by teamsteamdev** [comment]
Mongo.Collection.prototype.find would have been very clear to me! I am
familiar with the JS Object.prototype concept.

Thanks for your kind reply. You've obviously thought this out quite well!

I guess I was aware that these methods would be part of an instance of
Mongo.Collection, but I had not realized how Mongo.Collection.find would
imply find to be a static method. I haven't written any documentation
myself.

I suppose I'm used to docs for API Classes as seen on Google Apps Script
<https://developers.google.com/apps-script/reference/document/body>, Node
<https://nodejs.org/api/fs.html#fs_fs_write_fd_buffer_offset_length_position_callback>,
or Express <https://expressjs.com/en/4x/api.html>, which do not require
instantiation. Mongo.Collection is a different beast.

**Comment by teamsteamdev** [comment]
`Mongo.Collection.prototype.find` would have been very clear to me! I am
familiar with the JS `Object.prototype` concept.

Thanks for your great reply!

I guess I was aware that these methods would be part of an instance of
`Mongo.Collection`, but I had not thought through how `Mongo.Collection.find` would
imply `find` to be a static method. I haven't written any documentation
myself.

I suppose I'm used to docs for APIs like [Google Apps Script](https://developers.google.com/apps-script/reference/document/body), [Node](https://nodejs.org/api/fs.html#fs_fs_write_fd_buffer_offset_length_position_callback),
or [Express](https://expressjs.com/en/4x/api.html), which do not always require instantiation.

**Comment by teamsteamdev** [comment]
This might be pretty clear, but a little long.
![image](https://user-images.githubusercontent.com/23390212/28437102-07fe2268-6d5f-11e7-9a54-e7a0a5213de9.png)
@abernix Thanks for taking the time to explain. I wouldn't have known how to Google for this.
