### ISSUE TITLE
Text (font) size too small?

### ISSUE THREAD

**Issue by MiroHibler** [meteor/docs#18]
Is it only me (my eyes ;) that think text is a bit too tiny?

Sure, there's always [CMD][+] but the text size in a previous version was okay...

**Comment by rhettlivingston** [comment]
Perhaps I'm just getting too old, but I came here to make the same comment.

The previous version appears to have fonts in the important places (regular text, api text, and code) ranging from 16 to 20 points. This version seems to have fonts ranging from 12 to 16 points. 

I would vote for 16 across the board. I've never understood deemphasizing code and api. Those are the things I tend to look at first. And the code examples appear to be formatted well for display at 16 in that it doesn't cause annoying wrapping.

It is also surprising to see this in an age where design guidance is on an upward trend. Main fonts used to commonly be set at 14pts or event 12. Today's body font norm is 16pts and books and accessibility guides tend to advise that setting. 

Another data point is that bootstrap 4.0 increased their default to 16. And I see that Google search descriptions are 17.8 pts. That's very interesting because space is money to them.

**Comment by lorensr** [comment]
A couple people on meteor club slack also said it was too small. @dominicnguyen thoughts?

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
