### ISSUE TITLE
Meteor spacebar - not able to iterate an object

### ISSUE THREAD

**Issue by sakodiya2** [meteor/docs#339]
I'm struggling to iterating an object in meteor spacebar and I always got an error like 'unspecificed identifier'. Is there any way to resolve this issues ?

Also, I found another issue which cause we not able to fetch the object value based on the key while iterating an array. Please have a look at the below example -

let a = {‘1000’: 3, ‘4’: 89, ‘5’: 9898};
Also, I’ve one array i.e let b = [1000, 2000] (These values are generated dynamically but for example, I’m using the hard-coded values)

Now, I’m doing following in meteor side.
Spacebars.toHTML({a, b}, Assets.getText(‘private path of my file’));

**My HTML file -**
{{#each b}}
Index - {{this.[0]}}
// Now i want to fetch the ‘a’ object value basis on the b index value. as you can see here is
// that ‘1000’. how can we fetch the value from variable a like a[b] ? So that 3 would be printed
// here
{{/each}}

**Meteor version - METEOR@1.6**

**Comment by axelvaindal** [comment]
Hi,

I'm not sure of the real problem here. 
Is your issue somewhat related to the meteor documentation you can find [here](https://docs.meteor.com/) ?
It seems to me you're just having a technical issue using Spacebar and not with content of the Meteor documentation itselfs. If so, could you please close this issue and reopen inside the [blaze](https://github.com/meteor/blaze) repository directly or ask on the forum ? This way, they will be able to state if it's really a bug or if you're just missing something 🙂

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.
