### ISSUE TITLE
Why are some packages documented here and some not?

### ISSUE THREAD

**Issue by coagmano** [meteor/docs#488]
Someone asked a question about how to set a Content Security Policy on the forums recently and so I pointed them to the `browser-policy` package. 

Which is why I realised that `browser-policy` is missing from the docs, and further that it was removed in [900464a](https://github.com/meteor/docs/commit/900464a2c4c4513047b4231f7db3430e2cdf592c)

Is there currently a guideline for which core packages are included in the docs and which are not?

Personally, I think it belongs in the docs, especially with the growing push for sites to adopt CSPs. I also think that if `appcache` gets a spot in the docs, that `browser-policy` should as well

**Comment by lorensr** [comment]
I'm in favor of adding it back. At least a link to the readme

**Comment by abernix** [comment]
@coagmano `browser-policy` is still an important package and deserves to have documentation. 
 I suspect that some things have changed since the original reversal of that commit but if someone would prepare a PR for this, we'd certainly review it.

At the very least, thanks for this actionable issue!

**Comment by skirunman** [comment]
At least if, and until, the `browser-policy` packaged is deprecated and removed from the code base it should be documented. In fact, even if `Helmet` is recommended in the Meteor Guide it still should be documented as it is in the code base.
