### ISSUE TITLE
Docs show 1.8 as latest version

### ISSUE THREAD

**Issue by coagmano** [meteor/docs#660]
Not sure what's needed to get 1.9 in the version dropdown and as the default

**Comment by coagmano** [comment]
Seems with 1.10, the version has been updated, but now `/v1.7/` and `/v1.8/` don't work (showing blank page)

**Comment by damienfa** [comment]
Same here ! 🙁 
I work on a Meteor 1.8 project but I don't find any docs online.
I have found "https://docs.meteor.com/v1.8/" but it's only blank pages for days ... Is there any issue with the docs website ? `v1.7` et `v1.9 +` are available but not this one.

@coagmano , I can see `v1.7` but not `v1.8` , do something was updated since your last message ?

**Comment by coagmano** [comment]
Nope, 1.7 and 1.8 were both not working when I commented in March.

There's really not that much different in the docs between 1.8 and now though. If you really need the 1.8 docs, a workaround is to clone locally and run with Hexo.

**Comment by OlivierJM** [comment]
This looks fixed, the issue should be closed

**Comment by lorensr** [comment]
![image](https://user-images.githubusercontent.com/251288/103145762-95e6a600-470d-11eb-8bec-b699cccee1f3.png)
