### ISSUE TITLE
User profile is not created when account is created with accounts-password

### ISSUE THREAD

**Issue by laosb** [meteor/docs#81]
by @jrullmann on meteor/meteor#1369

*The 3-year-old ancient issue*

***1 Upvote*** From the [docs](http://docs.meteor.com/#accounts_createuser):
"By default the profile option is added directly to the new user document."

So I expect that if a user creates an account with accounts-password then a profile should be created for her.  Instead, I'm seeing that no profile is created.

Steps to reproduce:
1. Create the leaderboard example app (meteor create --example leaderboard)
2. Add accounts packages (meteor add accounts-ui accounts-password)
3. Add {{loginButtons}} to leaderboard.html
4. Run the app
5. Create an account with email/password
6. In the browser console, run Meteor.user().profile

Expected: Meteor.user().profile is an object
Actual: Meteor.user().profile is undefined

More info: 
- I'm using meteor version 0.6.5
- If I follow these steps using accounts-twitter the profile is created as expected

**Comment by laosb** [comment]
Solution: Update docs to explain it.

**Comment by abernix** [comment]
This conflicts with the concept of https://guide.meteor.com/accounts.html#dont-use-profile and #61.

Essentially, don't use `profile`.  Closing, but reopen if you feel differently. ;)

**Comment by MaxPleaner** [comment]
It does already say this in the accounts-multi doc [here](https://docs.meteor.com/api/accounts-multi.html)

> The default create user function simply copies options.profile into the new user document. Calling onCreateUser overrides the default hook. This can only be called once.

There are two issues I see:

1. The main thing which was non-intuitive to me, which is that `onCreateUser` _overwrites_ instead of acting as a _callback_.  I suppose I am to blame for not reading the docs before using the method, but still, I don't see this behavior being a feature. 
2. The notion that `profile` should not be used. Reading through the explanation of why it's not a good idea (the default write permission and the fact that people put arbitrary config data there), I see those as good points, but I'm not sure they outweigh the benefits, namely:
    1. the ability to get the username when using a 3rd party service, i.e. accounts-github
    2. the fact that it's intuitive and easily discoverable when poking around the `Meteor.user()` object

If `profile` needs manually configured access rules, then perhaps there should be a builtin warning about it. As it stands, though, unless one reads through the doc entry for each method they use (probably a good idea, but uncommon) then they will inevitable have to stumble upon this error in a manner similarly to that of myself: googling "meteor no user profile", reading through an issues thread, then following a link to the docs.
